### ISSUE TITLE
Integração com Pagar.me

### ISSUE THREAD

**Issue by filipedeschamps** [era/pay#1]
@era tudo bem meu caro?

Alguém te respondeu sobre a integração da nossa API em modo sandbox? Se não, só para registrar: temos este ambiente sim, basta fazer um cadastro em nossa Dashboard que automaticamente será criada uma `api_key` de testes: https://dashboard.pagar.me/#/signup?sid=1002

Com esta chave de testes é possível testar quase que todos os fluxos da nossa aplicação, é bem legal.

Um abração!

**Comment by era** [comment]
Olá @filipedeschamps :), tudo sim e com vc?

O @chrisenytc comentou sobre o cadastro. Acredito que começarei a integração com o Pagar.me no começo do próximo mês devido há algumas correrias pessoais.

Obrigado a vocês do pagar.me pelas respostas rápidas e anteciosas :). Realmente são uma empresa "dev-friendly" haha :).

Abraços

**Comment by filipedeschamps** [comment]
Sensacional, valeu meu caro :+1:
